print('you just got gamed')
print('did I really just get gamed!??!?!')
print('no way he just beeped me!!!?!?!!')
print('he did')
print('bruh')
print('work damnit')
print('game')
print('I HATE GAME')
print('omg it might acutally work this time :D')
print('damn it really be workin now huh')
print('it do be tho')
print('damn im good')
print('its not working anymore :(')
print('its working again!')
print('game')
print('it might do it!')
print('no it didnt')
#>:(
#bruhz